default:
  project_name: "{{ project_name }}"
  dependency_profile: "{{ dependency_profile }}"
  timezone: "Europe/London"
  seed: 12345
  paths:
    data_raw: "data/raw"
    data_external: "data/external"
    data_interim: "data/interim"
    data_processed: "data/processed"
    data_metadata: "data/metadata"
    outputs: "outputs"
    tables: "outputs/tables"
    figures: "outputs/figures"
    models: "outputs/models"
    logs: "outputs/logs"
    reports: "outputs/reports"

development:
  inherits: default

production:
  inherits: default
